### PR TITLE
Standards Maintenance Issue #452

### PR DESCRIPTION
**Pull request by dsbivan**
Set retirement dates for outstanding deprecated Register APIs

### CODE REVIEW

**Review by markverstege — COMMENTED** [review]
Note - the new obligation date schedule also needs to be updated. Remove from previous date and add updated counts to 15th Nov 2022

**Review by markverstege — COMMENTED** [review]
Might be worth noting in the release notes that you also changed the commencement dates for the v2 APIs extending the introduction dates.

**Comment by dsbivan** [comment]
> Might be worth noting in the release notes that you also changed the commencement dates for the v2 APIs extending the introduction dates.

This is addressed in issue 465 currently staged at: https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/173

**Comment by JamesMBligh** [comment]
@dsbivan, the conflicts in register.md are hard for me to resolve without detailed knowledge of the issues.  Could you please resolve the conflict so I can merge the PR?

**Comment by dsbivan** [comment]
> @dsbivan, the conflicts in register.md are hard for me to resolve without detailed knowledge of the issues. Could you please resolve the conflict so I can merge the PR?

done

**Pull request merged**
